package main

import (
	"embed"
	"fmt"
	"github.com/Admiral-Piett/musizticle/app"
	"github.com/Admiral-Piett/musizticle/app/daos"
	"github.com/Admiral-Piett/musizticle/app/utils"
	"io/fs"
	"log"
	"net/http"
)

var nextFS embed.FS

func main() {
	// Root at the `dist` folder generated by the Next.js app.
	distFS, err := fs.Sub(nextFS, "web/dist")
	if err != nil {
		log.Fatal(err)
	}

	appDaos := daos.InitializeDao()
	defer appDaos.CloseDao()
	app := app.New(appDaos, distFS)

	http.HandleFunc("/", app.ProxyHandler)

	app.Logger.Info("App up and running on http://localhost:", utils.PORT)
	err = http.ListenAndServe(fmt.Sprintf(":%s", utils.PORT), nil)
	if err != nil {
		log.Fatal(err)
	}
}
