name: Go

on:
  push:
    branches: [ main, ISSUE-28-automated-builds ]
  workflow_dispatch:
    inputs:
      tags:
        description: "Additional tag for build"
        required: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#       TODO - implement this when this repo gets a little more settled and I'm not pushing to main anymore.
      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
#        if: ${{ github.event.pull_request.merged == true }}
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
#        if: ${{ steps.release-label.outputs.level != null }}
      - name: See label outputs
        run: echo ${{ steps.release-label.outputs.level }}
      - name: See latest tag outputs
        run: echo ${{ steps.get-latest-tag.outputs.tag }}

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
#          level: ${{ steps.release-label.outputs.level }}
          level: ${{ steps.release-label.outputs.level }}

      - name: See bumped server version
        run: echo ${{ steps.action-bump-semver.outputs.new_version }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          push: true
#          platforms: linux/amd64,linux/arm/v7
#          tags: admiralpiett/musizticle:${{ github.sha }},admiralpiett/musizticle:latest
#
##      - uses: actions-ecosystem/action-push-tag@v1
##        if: ${{ steps.release-label.outputs.level != null }}
##        with:
##          tag: ${{ steps.bump-semver.outputs.new_version }}
##          message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
