name: Go

on:
  push:
    branches: [ main ]
#  TODO - decide if I need something like this.  Maybe for human-ish versioning.  TBD. (I can run with the sha for now)
#  workflow_dispatch:
#    inputs:
#      tags:
#        description: "Additional tag for build"
#        required: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7
          tags: admiralpiett/musizticle:${{env.SHORT_SHA}},admiralpiett/musizticle:latest
